spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://postgres:5432/orderdb  # хост = ім'я сервісу у docker-compose
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none   # Hibernate не валідую схему, Flyway створює таблиці

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true   # на випадок, якщо база вже існує
    clean-disabled: true        # безпечніше для dev/prod

  springdoc:
    swagger-ui:
      path: /swagger-ui.html
    api-docs:
      path: /v3/api-docs

logging:
  level:
    org.flywaydb: DEBUG   # щоб бачити виконання міграцій у логах
